[build]
command = "npm run build"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
status = 302
from = "/register"
to = "https://wlda547t.nocodb.com/#/nc/form/54ed6d40-726b-4af3-b1e4-994150a931f1"

[[redirects]]
from = "/volunteer/register"
to = "https://wlda547t.nocodb.com/#/nc/form/5f629525-e753-41b9-afa3-c61b8a9d5dd2"
status = 302
